### ISSUE TITLE
Create instance page crashed in mysterious way

### ISSUE THREAD

**Issue by edvgui** [inmanta/web-console#4100]
Here is the error being displayed:
![image](https://user-images.githubusercontent.com/20844316/192290493-dc5a4df2-3920-417c-80d1-8d9447af932c.png)
```
createFormState/<@http://192.168.2.47:8888/console/lsm/catalog/user_equipment/app.bundle.js:94629:38
createFormState@http://192.168.2.47:8888/console/lsm/catalog/user_equipment/app.bundle.js:94607:19
ServiceInstanceForm@http://192.168.2.47:8888/console/lsm/catalog/user_equipment/app.bundle.js:95183:11
Ch@http://192.168.2.47:8888/console/lsm/catalog/user_equipment/app.bundle.js:50821:137
ck@http://192.168.2.47:8888/console/lsm/catalog/user_equipment/app.bundle.js:50931:460
bk@http://192.168.2.47:8888/console/lsm/catalog/user_equipment/app.bundle.js:50914:349
ak@http://192.168.2.47:8888/console/lsm/catalog/user_equipment/app.bundle.js:50914:280
Tj@http://192.168.2.47:8888/console/lsm/catalog/user_equipment/app.bundle.js:50914:138
Lj@http://192.168.2.47:8888/console/lsm/catalog/user_equipment/app.bundle.js:50907:163
4448/jg/<@http://192.168.2.47:8888/console/lsm/catalog/user_equipment/app.bundle.js:50787:115
53/exports.unstable_runWithPriority@http://192.168.2.47:8888/console/lsm/catalog/user_equipment/app.bundle.js:51110:343
gg@http://192.168.2.47:8888/console/lsm/catalog/user_equipment/app.bundle.js:50786:325
jg@http://192.168.2.47:8888/console/lsm/catalog/user_equipment/app.bundle.js:50787:63
ig@http://192.168.2.47:8888/console/lsm/catalog/user_equipment/app.bundle.js:50786:428
Hb@http://192.168.2.47:8888/console/lsm/catalog/user_equipment/app.bundle.js:50956:101
gd@http://192.168.2.47:8888/console/lsm/catalog/user_equipment/app.bundle.js:50737:354

```

Here is how to reproduce it:

https://user-images.githubusercontent.com/20844316/192290839-36aec704-3106-4e51-9cc1-c7f4720fed3c.mp4

Web console commit hash: `edd03185e0ba74af29f03b80050702b17e5e3d9d`  
Service orchestrator version: `    5.2.1.dev20220926031235`

[db_dump.zip](https://github.com/inmanta/web-console/files/9646441/db_dump.zip)
> This db dump contains credentials to access the 5g lab (if you are in our internal network), you can mess up with it as much as you like, as long as @bartv is not doing a demo at the same time as you.  (If you leave the environment stopped this is fine)

**Comment by bartv** [comment]
On the same instance we get a similar issue:


https://user-images.githubusercontent.com/10819/192444601-0f15c633-4615-4206-bc2c-15bcacf98c35.mp4

The error is:
```
TypeError: Cannot create property 'data_networks' on string ''
    at http://192.168.2.47:8888/console/app.bundle.js:94629:36
    at Array.reduce (<anonymous>)
    at createFormState (http://192.168.2.47:8888/console/app.bundle.js:94607:19)
    at ServiceInstanceForm (http://192.168.2.47:8888/console/app.bundle.js:95183:11)
    at Ch (http://192.168.2.47:8888/console/app.bundle.js:50821:137)
    at ck (http://192.168.2.47:8888/console/app.bundle.js:50931:460)
    at bk (http://192.168.2.47:8888/console/app.bundle.js:50914:347)
    at ak (http://192.168.2.47:8888/console/app.bundle.js:50914:278)
    at Tj (http://192.168.2.47:8888/console/app.bundle.js:50914:138)
    at Lj (http://192.168.2.47:8888/console/app.bundle.js:50907:163)
```
