### ISSUE TITLE
console.warns in tests cases

### ISSUE THREAD

**Issue by matborowczyk** [inmanta/web-console#5143]
`PASS src/Slices/ServiceInventory/UI/Tabs/ConfigTab.test.tsx (5.374 s)

  ● Console

    console.warn

      Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.

      at node_modules/@patternfly/react-core/src/components/Card/CardHeader.tsx:102:17

      at updateContextConsumer (node_modules/react-dom/cjs/react-dom.development.js:21207:19)

      at beginWork (node_modules/react-dom/cjs/react-dom.development.js:21652:14)

      at beginWork$1 (node_modules/react-dom/cjs/react-dom.development.js:27426:14)

      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:26560:12)

      at workLoopSync (node_modules/react-dom/cjs/react-dom.development.js:26466:5)

      at renderRootSync (node_modules/react-dom/cjs/react-dom.development.js:26434:7)

      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:26085:20)

      at flushSyncCallbacks (node_modules/react-dom/cjs/react-dom.development.js:12042:22)

      at node_modules/react-dom/cjs/react-dom.development.js:25651:13

      at invokeTheCallbackFunction (node_modules/jsdom/lib/jsdom/living/generated/Function.js:19:26)

      at node_modules/jsdom/lib/jsdom/browser/Window.js:554:9

    console.warn

      Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.

      at node_modules/@patternfly/react-core/src/components/Card/CardHeader.tsx:102:17

      at updateContextConsumer (node_modules/react-dom/cjs/react-dom.development.js:21207:19)

      at beginWork (node_modules/react-dom/cjs/react-dom.development.js:21652:14)

      at beginWork$1 (node_modules/react-dom/cjs/react-dom.development.js:27426:14)

      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:26560:12)

      at workLoopSync (node_modules/react-dom/cjs/react-dom.development.js:26466:5)

      at renderRootSync (node_modules/react-dom/cjs/react-dom.development.js:26434:7)

      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:26085:20)

      at flushSyncCallbacks (node_modules/react-dom/cjs/react-dom.development.js:12042:22)

      at flushActQueue (node_modules/react/cjs/react.development.js:2667:24)

      at recursivelyFlushAsyncActWork (node_modules/react/cjs/react.development.js:2633:9)

      at node_modules/react/cjs/react.development.js:2545:15

    console.warn

      Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.

      at node_modules/@patternfly/react-core/src/components/Card/CardHeader.tsx:102:17

      at updateContextConsumer (node_modules/react-dom/cjs/react-dom.development.js:21207:19)

      at beginWork (node_modules/react-dom/cjs/react-dom.development.js:21652:14)

      at beginWork$1 (node_modules/react-dom/cjs/react-dom.development.js:27426:14)

      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:26560:12)

      at workLoopSync (node_modules/react-dom/cjs/react-dom.development.js:26466:5)

      at renderRootSync (node_modules/react-dom/cjs/react-dom.development.js:26434:7)

      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:26085:20)

      at flushSyncCallbacks (node_modules/react-dom/cjs/react-dom.development.js:12042:22)

      at node_modules/react-dom/cjs/react-dom.development.js:25651:13

      at invokeTheCallbackFunction (node_modules/jsdom/lib/jsdom/living/generated/Function.js:19:26)

      at node_modules/jsdom/lib/jsdom/browser/Window.js:554:9

    console.warn

      Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.

      at node_modules/@patternfly/react-core/src/components/Card/CardHeader.tsx:102:17

      at updateContextConsumer (node_modules/react-dom/cjs/react-dom.development.js:21207:19)

      at beginWork (node_modules/react-dom/cjs/react-dom.development.js:21652:14)

      at beginWork$1 (node_modules/react-dom/cjs/react-dom.development.js:27426:14)

      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:26560:12)

      at workLoopSync (node_modules/react-dom/cjs/react-dom.development.js:26466:5)

      at renderRootSync (node_modules/react-dom/cjs/react-dom.development.js:26434:7)

      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:26085:20)

      at flushSyncCallbacks (node_modules/react-dom/cjs/react-dom.development.js:12042:22)

      at flushActQueue (node_modules/react/cjs/react.development.js:2667:24)

      at recursivelyFlushAsyncActWork (node_modules/react/cjs/react.development.js:2633:9)

      at node_modules/react/cjs/react.development.js:2545:15

    console.warn

      Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.

      at node_modules/@patternfly/react-core/src/components/Card/CardHeader.tsx:102:17

      at updateContextConsumer (node_modules/react-dom/cjs/react-dom.development.js:21207:19)

      at beginWork (node_modules/react-dom/cjs/react-dom.development.js:21652:14)

      at beginWork$1 (node_modules/react-dom/cjs/react-dom.development.js:27426:14)

      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:26560:12)

      at workLoopSync (node_modules/react-dom/cjs/react-dom.development.js:26466:5)

      at renderRootSync (node_modules/react-dom/cjs/react-dom.development.js:26434:7)

      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:26085:20)

      at flushSyncCallbacks (node_modules/react-dom/cjs/react-dom.development.js:12042:22)

      at node_modules/react-dom/cjs/react-dom.development.js:25651:13

      at invokeTheCallbackFunction (node_modules/jsdom/lib/jsdom/living/generated/Function.js:19:26)

      at node_modules/jsdom/lib/jsdom/browser/Window.js:554:9

`

`
PASS src/Slices/Diagnose/UI/Diagnose.test.tsx (5.339 s)

  ● Console

    console.warn

      Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.

      at node_modules/@patternfly/react-core/src/components/Card/CardHeader.tsx:102:17

      at updateContextConsumer (node_modules/react-dom/cjs/react-dom.development.js:21207:19)

      at beginWork (node_modules/react-dom/cjs/react-dom.development.js:21652:14)

      at beginWork$1 (node_modules/react-dom/cjs/react-dom.development.js:27426:14)

      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:26560:12)

      at workLoopSync (node_modules/react-dom/cjs/react-dom.development.js:26466:5)

      at renderRootSync (node_modules/react-dom/cjs/react-dom.development.js:26434:7)

      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:26085:20)

      at flushSyncCallbacks (node_modules/react-dom/cjs/react-dom.development.js:12042:22)

      at node_modules/react-dom/cjs/react-dom.development.js:25651:13

      at invokeTheCallbackFunction (node_modules/jsdom/lib/jsdom/living/generated/Function.js:19:26)

      at node_modules/jsdom/lib/jsdom/browser/Window.js:554:9

    console.warn

      Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.

      at node_modules/@patternfly/react-core/src/components/Card/CardHeader.tsx:102:17

      at updateContextConsumer (node_modules/react-dom/cjs/react-dom.development.js:21207:19)

      at beginWork (node_modules/react-dom/cjs/react-dom.development.js:21652:14)

      at beginWork$1 (node_modules/react-dom/cjs/react-dom.development.js:27426:14)

      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:26560:12)

      at workLoopSync (node_modules/react-dom/cjs/react-dom.development.js:26466:5)

      at renderRootSync (node_modules/react-dom/cjs/react-dom.development.js:26434:7)

      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:26085:20)

      at flushSyncCallbacks (node_modules/react-dom/cjs/react-dom.development.js:12042:22)

      at node_modules/react-dom/cjs/react-dom.development.js:25651:13

      at invokeTheCallbackFunction (node_modules/jsdom/lib/jsdom/living/generated/Function.js:19:26)

      at node_modules/jsdom/lib/jsdom/browser/Window.js:554:9

`

`
PASS src/Slices/ServiceInventory/UI/Tabs/ConfigDetails.test.tsx (5.09 s)

  ● Console

    console.warn

      Selectable only cards should not contain any other actions. If you wish to include additional actions, use a clickable and selectable card.

      69 |     });

      70 |   });

    > 71 |   rerender(component({ enabled: true }));

         |   ^

      72 |   expect(

      73 |     await screen.findByRole("checkbox", { name: "enabled-True" }),

      74 |   ).toBeDisabled();

      at node_modules/@patternfly/react-core/src/components/Card/CardHeader.tsx:102:17

      at updateContextConsumer (node_modules/react-dom/cjs/react-dom.development.js:21207:19)

      at beginWork (node_modules/react-dom/cjs/react-dom.development.js:21652:14)

      at beginWork$1 (node_modules/react-dom/cjs/react-dom.development.js:27426:14)

      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:26560:12)

      at workLoopSync (node_modules/react-dom/cjs/react-dom.development.js:26466:5)

      at renderRootSync (node_modules/react-dom/cjs/react-dom.development.js:26434:7)

      at performConcurrentWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:25738:74)

      at flushActQueue (node_modules/react/cjs/react.development.js:2667:24)

      at act (node_modules/react/cjs/react.development.js:2582:11)

      at node_modules/@testing-library/react/dist/act-compat.js:63:25

      at renderRoot (node_modules/@testing-library/react/dist/pure.js:159:26)

      at rerender (node_modules/@testing-library/react/dist/pure.js:178:7)

      at Object.<anonymous> (src/Slices/ServiceInventory/UI/Tabs/ConfigDetails.test.tsx:71:3)

`

**Comment by LukasStordeur** [comment]
No console warns are remaining now that the upgrade to PF5 has been stabilized.
