### ISSUE TITLE
Toggle Th aren't accessible according to the warning in the console

### ISSUE THREAD

**Issue by matborowczyk** [inmanta/web-console#5905]
In the process of adding test for filtering reset i noticed warning in the console:

`  console.warn
    Th: Table headers must have an accessible name. If the Th is intended to be visually empty, pass in screenReaderText. If the Th contains only non-text, interactive content such as a checkbox or expand toggle, pass in an aria-label.

      at ThBase (node_modules/@patternfly/react-table/src/components/Table/Th.tsx:100:13)
      at renderWithHooks (node_modules/react-dom/cjs/react-dom.development.js:15486:18)
      at updateFunctionComponent (node_modules/react-dom/cjs/react-dom.development.js:19617:20)
      at beginWork (node_modules/react-dom/cjs/react-dom.development.js:21640:16)
      at beginWork$1 (node_modules/react-dom/cjs/react-dom.development.js:27465:14)
      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:26599:12)
      at workLoopSync (node_modules/react-dom/cjs/react-dom.development.js:26505:5)
      at renderRootSync (node_modules/react-dom/cjs/react-dom.development.js:26473:7)
      at performConcurrentWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:25777:74)
      at flushActQueue (node_modules/react/cjs/react.development.js:2667:24)
      at recursivelyFlushAsyncActWork (node_modules/react/cjs/react.development.js:2633:9)
      at node_modules/react/cjs/react.development.js:2545:15
`

to reproduce it just run test in for example ResourcePage.test.tsx

**Comment by LukasStordeur** [comment]
duplicate
